### ISSUE TITLE
can't build with cmake

### ISSUE THREAD

**Issue by chillenb** [NWChemEx/ChemCache#78]
With CMake>=3.20, I get the error

```
CMake Error at build/_deps/cmakepp_lang-src/cmake/cmakepp_lang/object/call.cmake:75 (message):
  No suitable overload of set_config_option(cmaizeproject, desc*)
Call Stack (most recent call first):
  build/_deps/cmakepp_lang-src/cmake/cmakepp_lang/object/call.cmake:124 (_cpp_object_call_guts)
  build/_deps/cmakepp_lang-src/cmake/cmakepp_lang/object/object.cmake:56 (_cpp_object_call)
  build/cmakepp/classes/CMaizeProject.cmake:43 (_cpp_object)
  build/_deps/cmaize-src/cmake/cmaize/user_api/cmaize_option.cmake:62 (CMaizeProject)
  build/_deps/cmaize-src/cmake/cmaize/user_api/cmaize_option.cmake:146 (cmaize_option)
  CMakeLists.txt:38 (cmaize_option_list)
```

Have you seen this happen before? I'm not getting any errors with CMake 3.19, only with >=3.20.

It also happens when I try to build SimDE and PluginPlay. Definitely something to do with CMaize.

**Comment by ryanmrichard** [comment]
I've not seen this before and I exclusively build with CMake > 3.20 (currently using 3.27 on this box). You mentioned you see this same error when you try to build PluginPlay? If so, I'm going to recommend we try to debug this issue in the context of building PluginPlay since it has less dependencies and builds quicker than either ChemCache or SimDE. To help with debugging it would also be great if you could post your toolchain file and the CMake command you use for configuring.

**Comment by chillenb** [comment]
Yes, it also happens with PluginPlay. I did a little experiment:
`cmake -H. -B./build -DCMAKE_TOOLCHAIN_FILE:PATH=$HOME/toolchain/empty.cmake`

where `$HOME/toolchain/empty.cmake` is an empty file.

With this build command, PluginPlay will produce the above error unless I add `set(BUILD_TESTING OFF)` or `set(BUILD_TESTING ON)` to the toolchain file. I guess doing so populates cmaize_option_list so it's no longer empty.

**Comment by ryanmrichard** [comment]
@chillenb Thanks for the additional information, that was really helpful. https://github.com/CMakePP/CMaize/pull/156 should have fixed this issue. Can you confirm?

**Comment by chillenb** [comment]
Yes, it works for me now with a totally empty toolchain file! Thanks for fixing it so quickly.
